package io.github.sahithchiluveru.readinstead.phone

import java.security.MessageDigest
import java.security.SecureRandom
import java.util.Base64

/**
 * The Access Key: a random secret, generated by the TV and carried in the QR code, that
 * every Phone Page request must present. Resetting it locks out every connected phone.
 */
class AccessKey(private val store: Store) {
    /** Where the key is persisted, so phones stay connected across app restarts. */
    interface Store {
        fun load(): String?
        fun save(key: String)
    }

    private var key: String = store.load() ?: generate().also(store::save)

    val current: String
        @Synchronized get() = key

    @Synchronized
    fun reset(): String = generate().also {
        key = it
        store.save(it)
    }

    fun matches(candidate: String?): Boolean =
        candidate != null && MessageDigest.isEqual(candidate.toByteArray(), current.toByteArray())

    private companion object {
        val random = SecureRandom()

        /** 128 random bits, URL-safe so the key can sit in the QR code's address. */
        fun generate(): String =
            Base64.getUrlEncoder().withoutPadding().encodeToString(ByteArray(16).also(random::nextBytes))
    }
}
